<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="168753" started-at="2017-12-21T21:02:21Z" finished-at="2017-12-21T21:05:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="168753" started-at="2017-12-21T21:02:21Z" finished-at="2017-12-21T21:05:10Z">
      <class name="by.htp.selenium.mailtest.MailRuTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="setUp" is-config="true" duration-ms="9475" started-at="2017-12-21T23:02:21Z" description="Init browser" finished-at="2017-12-21T23:02:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="invalidLogin()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="invalidLogin" duration-ms="3918" started-at="2017-12-21T23:02:31Z" description="negative" finished-at="2017-12-21T23:02:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLogin -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="setUp" is-config="true" duration-ms="0" started-at="2017-12-21T23:02:35Z" description="Init browser" finished-at="2017-12-21T23:02:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validLogin()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="validLogin" duration-ms="10038" started-at="2017-12-21T23:02:35Z" description="possitive" finished-at="2017-12-21T23:02:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="setUp" is-config="true" duration-ms="0" started-at="2017-12-21T23:02:45Z" description="Init browser" finished-at="2017-12-21T23:02:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="sendCorrectMessage()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="sendCorrectMessage" duration-ms="16324" started-at="2017-12-21T23:02:45Z" depends-on-methods="by.htp.selenium.mailtest.MailRuTest.validLogin" finished-at="2017-12-21T23:03:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendCorrectMessage -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="setUp" is-config="true" duration-ms="0" started-at="2017-12-21T23:03:01Z" description="Init browser" finished-at="2017-12-21T23:03:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="sendEmptyMessage()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="sendEmptyMessage" duration-ms="11018" started-at="2017-12-21T23:03:01Z" description="negative" depends-on-methods="by.htp.selenium.mailtest.MailRuTest.validLogin" finished-at="2017-12-21T23:03:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Вы уверены, что хотите отправить пустое письмо?] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Вы уверены, что хотите отправить пустое письмо?] but found []
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at by.htp.selenium.mailtest.MailRuTest.sendEmptyMessage(MailRuTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendEmptyMessage -->
        <test-method status="PASS" signature="sendMessageWithoutEmail()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="sendMessageWithoutEmail" duration-ms="9575" started-at="2017-12-21T23:03:12Z" description="negative" depends-on-methods="by.htp.selenium.mailtest.MailRuTest.validLogin" finished-at="2017-12-21T23:03:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendMessageWithoutEmail -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="setUp" is-config="true" duration-ms="0" started-at="2017-12-21T23:03:12Z" description="Init browser" finished-at="2017-12-21T23:03:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="setUp" is-config="true" duration-ms="0" started-at="2017-12-21T23:03:22Z" description="Init browser" finished-at="2017-12-21T23:03:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="writeMessageIncorrectEmail()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="writeMessageIncorrectEmail" duration-ms="9617" started-at="2017-12-21T23:03:22Z" depends-on-methods="by.htp.selenium.mailtest.MailRuTest.validLogin" finished-at="2017-12-21T23:03:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at by.htp.selenium.mailtest.MailRuTest.writeMessageIncorrectEmail(MailRuTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- writeMessageIncorrectEmail -->
        <test-method status="PASS" signature="close()[pri:0, instance:by.htp.selenium.mailtest.MailRuTest@1565ec2]" name="close" is-config="true" duration-ms="98735" started-at="2017-12-21T23:03:31Z" finished-at="2017-12-21T23:05:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- by.htp.selenium.mailtest.MailRuTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
